"""Add event fields

Revision ID: 5ea4b8f709cc
Revises: 
Create Date: 2025-06-23 05:33:50.482954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea4b8f709cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('max_pupils', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('max_age', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'cost')
    op.drop_column('events', 'max_age')
    op.drop_column('events', 'min_age')
    op.drop_column('events', 'max_pupils')
    # ### end Alembic commands ###
