"""add child and booking models, extend event for booking rules

Revision ID: 717e04720dbd
Revises: 6886710e270d
Create Date: 2025-06-23 07:50:42.245244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717e04720dbd'
down_revision: Union[str, None] = '6886710e270d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('recommended_age', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('is_multi_part', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('part_number', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('location_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location_details')
    op.drop_column('events', 'part_number')
    op.drop_column('events', 'is_multi_part')
    op.drop_column('events', 'recommended_age')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
