"""Add cancellation tracking fields to bookings

Revision ID: 873799b69d1d
Revises: 9129d77ff3ad
Create Date: 2025-06-30 08:40:38.713575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873799b69d1d'
down_revision: Union[str, None] = '9129d77ff3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adult_bookings', sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
    op.add_column('adult_bookings', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('adult_bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('adult_bookings', sa.Column('cancellation_approved_by', sa.Integer(), nullable=True))
    op.add_column('adult_bookings', sa.Column('cancellation_approved_at', sa.DateTime(), nullable=True))
    op.add_column('adult_bookings', sa.Column('refund_processed', sa.Boolean(), nullable=True))
    op.add_column('adult_bookings', sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('adult_bookings', sa.Column('refund_processed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'adult_bookings', 'users', ['cancellation_approved_by'], ['id'])
    op.add_column('bookings', sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_approved_by', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_approved_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('refund_processed', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('refund_processed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['cancellation_approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'refund_processed_at')
    op.drop_column('bookings', 'refund_amount')
    op.drop_column('bookings', 'refund_processed')
    op.drop_column('bookings', 'cancellation_approved_at')
    op.drop_column('bookings', 'cancellation_approved_by')
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'cancellation_requested_at')
    op.drop_constraint(None, 'adult_bookings', type_='foreignkey')
    op.drop_column('adult_bookings', 'refund_processed_at')
    op.drop_column('adult_bookings', 'refund_amount')
    op.drop_column('adult_bookings', 'refund_processed')
    op.drop_column('adult_bookings', 'cancellation_approved_at')
    op.drop_column('adult_bookings', 'cancellation_approved_by')
    op.drop_column('adult_bookings', 'cancellation_reason')
    op.drop_column('adult_bookings', 'cancelled_at')
    op.drop_column('adult_bookings', 'cancellation_requested_at')
    # ### end Alembic commands ###
