"""Add agent tables for AI chat functionality

Revision ID: b02384085cc1
Revises: cb23f7d414cd
Create Date: 2025-06-29 03:58:58.496687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02384085cc1'
down_revision: Union[str, None] = 'cb23f7d414cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_agent_sessions_conversation_id'), table_name='agent_sessions')
    op.drop_index(op.f('idx_chat_conversations_status'), table_name='chat_conversations')
    op.drop_index(op.f('idx_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('idx_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_created_at'), table_name='chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_conversations_status'), 'chat_conversations', ['status'], unique=False)
    op.create_index(op.f('idx_agent_sessions_conversation_id'), 'agent_sessions', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
