"""add facebook oauth fields

Revision ID: fb_oauth_001
Revises: 8d980eb7c7cc
Create Date: 2024-01-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb_oauth_001'
down_revision: Union[str, None] = '8d980eb7c7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add Facebook OAuth fields to users table
    op.add_column('users', sa.Column('facebook_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    
    # Make hashed_password nullable for OAuth users
    op.alter_column('users', 'hashed_password', nullable=True)
    
    # Create indexes
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    
    # Set default auth_provider for existing users
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'facebook_id')
    
    # Make hashed_password not nullable again
    op.alter_column('users', 'hashed_password', nullable=False)
    # ### end Alembic commands ### 